### ISSUE TITLE
Type checking is incompatible with Perl duck-typing

### ISSUE THREAD

**Issue by Corion** [oalders/http-cookiemonster#1]
This module does not co-operate with duck-typed cookie jars like `HTTP::CookieJar`:
```
  use LWP::UserAgent;
  use HTTP::CookieJar::LWP;
  use LWP::ConsoleLogger::Easy 'debug_ua';

  my $ua = LWP::UserAgent->new(
    cookie_jar => HTTP::CookieJar::LWP->new
  );
  
  debug_ua( $ua );
  
  $ua->get('https://cpan.org');
```

dies with

 ```
isa check for "cookie_jar" failed: HTTP::Cookies object expected at C:/strawberr
y-perl-5.26.0.1-64bit/perl/site/lib/LWP/ConsoleLogger.pm line 302.
```

The "type" check should check that the interface as provided by HTTP::Cookies is implemented, maybe with one or more `->can()` checks instead of insisting that objects derive from HTTP::Cookies.

**Comment by oalders** [comment]
Thanks @Corion.  This needs to be fixed. I'll put it on my list, but I would also happily accept a patch.

**Comment by oalders** [comment]
Actually, I think this might be better fixed in `LWP::ConsoleLogger`.  This module was just supposed to be a wrapper around `HTTP::Cookies`.  The real problem is that `LWP::ConsoleLogger` is assuming that every UA will have a cookie jar with the same interface.

**Comment by oalders** [comment]
Fixed in `LWP::ConsoleLogger` and released to CPAN.  Thanks for reporting @Corion!
