### ISSUE TITLE
uses Data::Serializer in tests, which now fail tests

### ISSUE THREAD

**Issue by karenetheridge** [oalders/http-cookiemonster#4]
Data::Serializer is now failing tests due to an update in the YAML libraries that turns off the LoadBlessed option by default.

Data::Serializer hasn't been updated in many years and the author is difficult to reach; since you just use it in tests to store a cookie, I suggest you switch to something else, perhaps JSON, to store your test data.

**Comment by oalders** [comment]
Thanks @karenetheridge!
