### ISSUE TITLE
A useless dependency on WWW::Mechanize

### ISSUE THREAD

**Issue by ppisar** [oalders/http-cookiemonster#7]
HTTP-CookieMonster-0.10 added a test dependency on WWW::Mechanize. But that module is actually not used anywhere. I recommend removing WWW::Mechanize from Makefile.PL:36.

**Comment by oalders** [comment]
There's a test that checks the `SYNOPSIS` code.  That test fails because `WWW::Mechanize` needs to be installed in order to `eval` that code.  So it's used in a roundabout way.  I'm fine with removing the dependency, though.  Thanks for the report.
